"""add email_rule

Revision ID: 4fd06e42aa9c
Revises: e39e98f69a8c
Create Date: 2023-11-12 16:40:55.377658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd06e42aa9c'
down_revision = 'e39e98f69a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_rule', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_column('email_rule')

    # ### end Alembic commands ###
